### PR TITLE
Fixed "'module' is defined but never used." issue

### PR DESCRIPTION
**Pull request by yesji**
Fixed "'module' is defined but never used." issue. If this is the expected solution, I will go forward and use the same solution for similar issues.

### CODE REVIEW

**Comment by simon987** [comment]
Yes, you can go ahead and do the other ones !

**Comment by yesji** [comment]
Thanks for the reply @simon987 Fixed all the "'Module' is defined but never used issues"

**Comment by simon987** [comment]
Thank you!

**Comment by yesji** [comment]
Thanks @simon987 :)

**Pull request merged**
