### PR TITLE
Added functionality to archive list of saves when the game server exits.

### PR DESCRIPTION
**Pull request by StevenBerdak**
The number of saves that will be archived can be modified using
max_archive_size in config.properties. Added shutdown hook to Main.java
to handle dumping of zip files. Essential functions are in
ZipUtils.java.

### CODE REVIEW

**Comment by StevenBerdak** [comment]
I'm not sure why it is formatted the way it is when you review the commit but no actual lines were deleted.

**Comment by StevenBerdak** [comment]
Oh ok so we are simply going to wrap the sava data in a single zip file. I guess I didn't completely understand the original intent. I will update it. Thanks :-)

**Comment by simon987** [comment]
It doesn't have to be a single zip file, I think it would be safer to use a single zip file for each save

**Comment by StevenBerdak** [comment]
I might try storing the files as temp files in a hidden folder, then they can be managed from there. Let me think on this.

**Comment by simon987** [comment]
I think you are overcomplicating it. What I would do is: (save function) create an empty zip file, and put the existing save.json in it. close that zip file and place it in the /save/ folder. Then check how many individual files are in this folder and delete the oldest ones if there's too many. Then ovewrite the save.json file with the new save as per usual. Sorry if the issue description wasn't very clear

**Pull request closed without merging**
